export enum RequestStageType {
    TERRAFORM_ALLOCATION,
    NETWORKING_ANSIBLE_ALLOCATION,
    USER_ANSIBLE_ALLOCATION,
    TERRAFORM_CLEANUP,
    NETWORKING_ANSIBLE_CLEANUP,
    USER_ANSIBLE_CLEANUP,
}
